/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125VerifyRouteImport } from './routes/{-$locale}/verify'
import { Route as Char123LocaleChar125SigninRouteImport } from './routes/{-$locale}/signin'
import { Route as Char123LocaleChar125HomeRouteImport } from './routes/{-$locale}/home'
import { Route as Char123LocaleChar125DeclareRouteImport } from './routes/{-$locale}/declare'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char123LocaleChar125JoinIndexRouteImport } from './routes/{-$locale}/join/index'
import { Route as Char123LocaleChar125RegionIndexRouteImport } from './routes/{-$locale}/$region/index'
import { Route as Char123LocaleChar125JoinRegisterRouteImport } from './routes/{-$locale}/join/register'
import { Route as Char123LocaleChar125RegionDistrictRouteImport } from './routes/{-$locale}/$region/$district'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125VerifyRoute =
  Char123LocaleChar125VerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SigninRoute =
  Char123LocaleChar125SigninRouteImport.update({
    id: '/signin',
    path: '/signin',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125HomeRoute =
  Char123LocaleChar125HomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DeclareRoute =
  Char123LocaleChar125DeclareRouteImport.update({
    id: '/declare',
    path: '/declare',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125JoinIndexRoute =
  Char123LocaleChar125JoinIndexRouteImport.update({
    id: '/join/',
    path: '/join/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125RegionIndexRoute =
  Char123LocaleChar125RegionIndexRouteImport.update({
    id: '/$region/',
    path: '/$region/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125JoinRegisterRoute =
  Char123LocaleChar125JoinRegisterRouteImport.update({
    id: '/join/register',
    path: '/join/register',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125RegionDistrictRoute =
  Char123LocaleChar125RegionDistrictRouteImport.update({
    id: '/$region/$district',
    path: '/$region/$district',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/{-$locale}/declare': typeof Char123LocaleChar125DeclareRoute
  '/{-$locale}/home': typeof Char123LocaleChar125HomeRoute
  '/{-$locale}/signin': typeof Char123LocaleChar125SigninRoute
  '/{-$locale}/verify': typeof Char123LocaleChar125VerifyRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/{-$locale}/$region/$district': typeof Char123LocaleChar125RegionDistrictRoute
  '/{-$locale}/join/register': typeof Char123LocaleChar125JoinRegisterRoute
  '/{-$locale}/$region/': typeof Char123LocaleChar125RegionIndexRoute
  '/{-$locale}/join/': typeof Char123LocaleChar125JoinIndexRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/{-$locale}/declare': typeof Char123LocaleChar125DeclareRoute
  '/{-$locale}/home': typeof Char123LocaleChar125HomeRoute
  '/{-$locale}/signin': typeof Char123LocaleChar125SigninRoute
  '/{-$locale}/verify': typeof Char123LocaleChar125VerifyRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/{-$locale}/$region/$district': typeof Char123LocaleChar125RegionDistrictRoute
  '/{-$locale}/join/register': typeof Char123LocaleChar125JoinRegisterRoute
  '/{-$locale}/$region': typeof Char123LocaleChar125RegionIndexRoute
  '/{-$locale}/join': typeof Char123LocaleChar125JoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/{-$locale}/declare': typeof Char123LocaleChar125DeclareRoute
  '/{-$locale}/home': typeof Char123LocaleChar125HomeRoute
  '/{-$locale}/signin': typeof Char123LocaleChar125SigninRoute
  '/{-$locale}/verify': typeof Char123LocaleChar125VerifyRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/{-$locale}/$region/$district': typeof Char123LocaleChar125RegionDistrictRoute
  '/{-$locale}/join/register': typeof Char123LocaleChar125JoinRegisterRoute
  '/{-$locale}/$region/': typeof Char123LocaleChar125RegionIndexRoute
  '/{-$locale}/join/': typeof Char123LocaleChar125JoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/{-$locale}/declare'
    | '/{-$locale}/home'
    | '/{-$locale}/signin'
    | '/{-$locale}/verify'
    | '/{-$locale}/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/{-$locale}/$region/$district'
    | '/{-$locale}/join/register'
    | '/{-$locale}/$region/'
    | '/{-$locale}/join/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/{-$locale}/declare'
    | '/{-$locale}/home'
    | '/{-$locale}/signin'
    | '/{-$locale}/verify'
    | '/{-$locale}'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/{-$locale}/$region/$district'
    | '/{-$locale}/join/register'
    | '/{-$locale}/$region'
    | '/{-$locale}/join'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/{-$locale}/declare'
    | '/{-$locale}/home'
    | '/{-$locale}/signin'
    | '/{-$locale}/verify'
    | '/{-$locale}/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/{-$locale}/$region/$district'
    | '/{-$locale}/join/register'
    | '/{-$locale}/$region/'
    | '/{-$locale}/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/verify': {
      id: '/{-$locale}/verify'
      path: '/verify'
      fullPath: '/{-$locale}/verify'
      preLoaderRoute: typeof Char123LocaleChar125VerifyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/signin': {
      id: '/{-$locale}/signin'
      path: '/signin'
      fullPath: '/{-$locale}/signin'
      preLoaderRoute: typeof Char123LocaleChar125SigninRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/home': {
      id: '/{-$locale}/home'
      path: '/home'
      fullPath: '/{-$locale}/home'
      preLoaderRoute: typeof Char123LocaleChar125HomeRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/declare': {
      id: '/{-$locale}/declare'
      path: '/declare'
      fullPath: '/{-$locale}/declare'
      preLoaderRoute: typeof Char123LocaleChar125DeclareRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/join/': {
      id: '/{-$locale}/join/'
      path: '/join'
      fullPath: '/{-$locale}/join/'
      preLoaderRoute: typeof Char123LocaleChar125JoinIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$region/': {
      id: '/{-$locale}/$region/'
      path: '/$region'
      fullPath: '/{-$locale}/$region/'
      preLoaderRoute: typeof Char123LocaleChar125RegionIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/join/register': {
      id: '/{-$locale}/join/register'
      path: '/join/register'
      fullPath: '/{-$locale}/join/register'
      preLoaderRoute: typeof Char123LocaleChar125JoinRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$region/$district': {
      id: '/{-$locale}/$region/$district'
      path: '/$region/$district'
      fullPath: '/{-$locale}/$region/$district'
      preLoaderRoute: typeof Char123LocaleChar125RegionDistrictRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125DeclareRoute: typeof Char123LocaleChar125DeclareRoute
  Char123LocaleChar125HomeRoute: typeof Char123LocaleChar125HomeRoute
  Char123LocaleChar125SigninRoute: typeof Char123LocaleChar125SigninRoute
  Char123LocaleChar125VerifyRoute: typeof Char123LocaleChar125VerifyRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125RegionDistrictRoute: typeof Char123LocaleChar125RegionDistrictRoute
  Char123LocaleChar125JoinRegisterRoute: typeof Char123LocaleChar125JoinRegisterRoute
  Char123LocaleChar125RegionIndexRoute: typeof Char123LocaleChar125RegionIndexRoute
  Char123LocaleChar125JoinIndexRoute: typeof Char123LocaleChar125JoinIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125DeclareRoute: Char123LocaleChar125DeclareRoute,
    Char123LocaleChar125HomeRoute: Char123LocaleChar125HomeRoute,
    Char123LocaleChar125SigninRoute: Char123LocaleChar125SigninRoute,
    Char123LocaleChar125VerifyRoute: Char123LocaleChar125VerifyRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125RegionDistrictRoute:
      Char123LocaleChar125RegionDistrictRoute,
    Char123LocaleChar125JoinRegisterRoute:
      Char123LocaleChar125JoinRegisterRoute,
    Char123LocaleChar125RegionIndexRoute: Char123LocaleChar125RegionIndexRoute,
    Char123LocaleChar125JoinIndexRoute: Char123LocaleChar125JoinIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
